version: 10.0.0.{build}
image: Visual Studio 2017

environment:
  STRIPE_TEST_KEY:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY
  STRIPE_RECIPIENT_KEY:
    secure: +eN5/SMeEbaqOR5VeM62dIJ8CGEzb74+3+feLb60jnYhQJ5enX2IwdFyfIy6/5UZ

deploy:
- provider: NuGet
  api_key:
    secure: D6ys+uEckSSs1hTQ0/io7wKytQnGH32FMzsPCRBVT1L6wmGe2pj3bmVNgw/xKBqM
  on:
    branch: master

install:
- ps: Import-Module .\build\build.psm1

before_build:
- ps: Invoke-Restore

build_script:
- ps: Invoke-Build

test_script:
- ps: Invoke-Test

after_build:
- ps: Invoke-Pack

# these commands force appveyor to offer an RDP session for debugging
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
