version: 6.11.1.{build}
image: Visual Studio 2015

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

install:
- ps: Import-Module .\build\build.psm1

before_build:
- ps: Invoke-Restore

build_script:
- ps: Invoke-Build

test_script:
- ps: Invoke-Test

after_build:
- ps: Invoke-Pack

artifacts:
  - path: src
    name: src-folder
    type: zip
