version: 6.13.0.{build}
image: Visual Studio 2015

environment:
  stripe_test_secret_key:
    secure: +p/EWA8+0B64k7a88nb6ZiSTcv6TIukyhQQU2Ljf7jNVtwVZXhJtNf5LdemV7EuY

deploy:
- provider: NuGet
  api_key:
    secure: D6ys+uEckSSs1hTQ0/io7wKytQnGH32FMzsPCRBVT1L6wmGe2pj3bmVNgw/xKBqM
  on:
    branch: master

install:
- ps: Import-Module .\build\build.psm1

before_build:
- ps: Invoke-Restore

build_script:
- ps: Invoke-Build

test_script:
- ps: Invoke-Test

after_build:
- ps: Invoke-Pack
